#spring boot application
spring:
  application:
    name: fixfunds-dao
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fixfunds
    username: fixfunds
    password: fixfunds

mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.jml.fixfunds.domain

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
  port: 9099

logging:
  level:
    root: WARN
    sample:
      mybatis:
        mapper: TRACE

