package com.jml.fixfunds.domain;

import java.io.Serializable;
import java.util.Date;

public class FfBaseCommitteeMember implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.PK_FF_BASE_OWNER_ID
     *
     * @mbggenerated
     */
    private String pkFfBaseOwnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.PK_ORG_ID
     *
     * @mbggenerated
     */
    private String pkOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.DUTY
     *
     * @mbggenerated
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.START_DATE
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.END_DATE
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.IS_DELETED
     *
     * @mbggenerated
     */
    private Float isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private Date sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_ID
     *
     * @mbggenerated
     */
    private String sysCreateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_ID
     *
     * @mbggenerated
     */
    private String sysUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_ID
     *
     * @mbggenerated
     */
    private String sysDeleteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FF_BASE_COMMITTEE_MEMBER
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.ID
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.ID
     *
     * @param id the value for FF_BASE_COMMITTEE_MEMBER.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.PK_FF_BASE_OWNER_ID
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.PK_FF_BASE_OWNER_ID
     *
     * @mbggenerated
     */
    public String getPkFfBaseOwnerId() {
        return pkFfBaseOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.PK_FF_BASE_OWNER_ID
     *
     * @param pkFfBaseOwnerId the value for FF_BASE_COMMITTEE_MEMBER.PK_FF_BASE_OWNER_ID
     *
     * @mbggenerated
     */
    public void setPkFfBaseOwnerId(String pkFfBaseOwnerId) {
        this.pkFfBaseOwnerId = pkFfBaseOwnerId == null ? null : pkFfBaseOwnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.PK_ORG_ID
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.PK_ORG_ID
     *
     * @mbggenerated
     */
    public String getPkOrgId() {
        return pkOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.PK_ORG_ID
     *
     * @param pkOrgId the value for FF_BASE_COMMITTEE_MEMBER.PK_ORG_ID
     *
     * @mbggenerated
     */
    public void setPkOrgId(String pkOrgId) {
        this.pkOrgId = pkOrgId == null ? null : pkOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.DUTY
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.DUTY
     *
     * @mbggenerated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.DUTY
     *
     * @param duty the value for FF_BASE_COMMITTEE_MEMBER.DUTY
     *
     * @mbggenerated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.START_DATE
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.START_DATE
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.START_DATE
     *
     * @param startDate the value for FF_BASE_COMMITTEE_MEMBER.START_DATE
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.END_DATE
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.END_DATE
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.END_DATE
     *
     * @param endDate the value for FF_BASE_COMMITTEE_MEMBER.END_DATE
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.REMARK
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.REMARK
     *
     * @param remark the value for FF_BASE_COMMITTEE_MEMBER.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.IS_DELETED
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.IS_DELETED
     *
     * @mbggenerated
     */
    public Float getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.IS_DELETED
     *
     * @param isDeleted the value for FF_BASE_COMMITTEE_MEMBER.IS_DELETED
     *
     * @mbggenerated
     */
    public void setIsDeleted(Float isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.VERSION
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.VERSION
     *
     * @param version the value for FF_BASE_COMMITTEE_MEMBER.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_TIME
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(Date sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_TIME
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(Date sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_TIME
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(Date sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_ID
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_ID
     *
     * @mbggenerated
     */
    public String getSysCreateId() {
        return sysCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_ID
     *
     * @param sysCreateId the value for FF_BASE_COMMITTEE_MEMBER.SYS_CREATE_ID
     *
     * @mbggenerated
     */
    public void setSysCreateId(String sysCreateId) {
        this.sysCreateId = sysCreateId == null ? null : sysCreateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_ID
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_ID
     *
     * @mbggenerated
     */
    public String getSysUpdateId() {
        return sysUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_ID
     *
     * @param sysUpdateId the value for FF_BASE_COMMITTEE_MEMBER.SYS_UPDATE_ID
     *
     * @mbggenerated
     */
    public void setSysUpdateId(String sysUpdateId) {
        this.sysUpdateId = sysUpdateId == null ? null : sysUpdateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_ID
     *
     * @return the value of FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_ID
     *
     * @mbggenerated
     */
    public String getSysDeleteId() {
        return sysDeleteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_ID
     *
     * @param sysDeleteId the value for FF_BASE_COMMITTEE_MEMBER.SYS_DELETE_ID
     *
     * @mbggenerated
     */
    public void setSysDeleteId(String sysDeleteId) {
        this.sysDeleteId = sysDeleteId == null ? null : sysDeleteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FF_BASE_COMMITTEE_MEMBER
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pkFfBaseOwnerId=").append(pkFfBaseOwnerId);
        sb.append(", pkOrgId=").append(pkOrgId);
        sb.append(", duty=").append(duty);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", remark=").append(remark);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", version=").append(version);
        sb.append(", sysCreateTime=").append(sysCreateTime);
        sb.append(", sysUpdateTime=").append(sysUpdateTime);
        sb.append(", sysDeleteTime=").append(sysDeleteTime);
        sb.append(", sysCreateId=").append(sysCreateId);
        sb.append(", sysUpdateId=").append(sysUpdateId);
        sb.append(", sysDeleteId=").append(sysDeleteId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}