package com.jml.fixfunds.domain;

import java.io.Serializable;
import java.util.Date;

public class FfBaseFacility implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.FACILITY_TYPE_CODE
     *
     * @mbggenerated
     */
    private String facilityTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.PK_PROPERTY_AREA_ID
     *
     * @mbggenerated
     */
    private String pkPropertyAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.FACILITY_NAME
     *
     * @mbggenerated
     */
    private String facilityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.OWNER_TYPE
     *
     * @mbggenerated
     */
    private String ownerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SCOPE_TYPE
     *
     * @mbggenerated
     */
    private String scopeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.POSITION
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.BRAND
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SPECIFICATION
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.INSTALL_DATE
     *
     * @mbggenerated
     */
    private Date installDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.ENABLE_DATE
     *
     * @mbggenerated
     */
    private Date enableDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.DELIVERY_DATE
     *
     * @mbggenerated
     */
    private Date deliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.WARRANTY_DATE
     *
     * @mbggenerated
     */
    private Date warrantyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.RELEASE_DATE
     *
     * @mbggenerated
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SUPPLY_UNIT
     *
     * @mbggenerated
     */
    private String supplyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.FACILITY_STATUS
     *
     * @mbggenerated
     */
    private String facilityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.FACILITY_BELONG
     *
     * @mbggenerated
     */
    private String facilityBelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.POSSESSOR
     *
     * @mbggenerated
     */
    private String possessor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.RESPONSOR
     *
     * @mbggenerated
     */
    private String responsor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SCRAP_DATE
     *
     * @mbggenerated
     */
    private Date scrapDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SCRAP_REASON
     *
     * @mbggenerated
     */
    private String scrapReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.RESPONSE_METHOD
     *
     * @mbggenerated
     */
    private String responseMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.IS_DELETED
     *
     * @mbggenerated
     */
    private Float isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private Date sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SYS_CREATE_ID
     *
     * @mbggenerated
     */
    private String sysCreateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SYS_UPDATE_ID
     *
     * @mbggenerated
     */
    private String sysUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FF_BASE_FACILITY.SYS_DELETE_ID
     *
     * @mbggenerated
     */
    private String sysDeleteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FF_BASE_FACILITY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.ID
     *
     * @return the value of FF_BASE_FACILITY.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.ID
     *
     * @param id the value for FF_BASE_FACILITY.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.FACILITY_TYPE_CODE
     *
     * @return the value of FF_BASE_FACILITY.FACILITY_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getFacilityTypeCode() {
        return facilityTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.FACILITY_TYPE_CODE
     *
     * @param facilityTypeCode the value for FF_BASE_FACILITY.FACILITY_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setFacilityTypeCode(String facilityTypeCode) {
        this.facilityTypeCode = facilityTypeCode == null ? null : facilityTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.PK_PROPERTY_AREA_ID
     *
     * @return the value of FF_BASE_FACILITY.PK_PROPERTY_AREA_ID
     *
     * @mbggenerated
     */
    public String getPkPropertyAreaId() {
        return pkPropertyAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.PK_PROPERTY_AREA_ID
     *
     * @param pkPropertyAreaId the value for FF_BASE_FACILITY.PK_PROPERTY_AREA_ID
     *
     * @mbggenerated
     */
    public void setPkPropertyAreaId(String pkPropertyAreaId) {
        this.pkPropertyAreaId = pkPropertyAreaId == null ? null : pkPropertyAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.FACILITY_NAME
     *
     * @return the value of FF_BASE_FACILITY.FACILITY_NAME
     *
     * @mbggenerated
     */
    public String getFacilityName() {
        return facilityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.FACILITY_NAME
     *
     * @param facilityName the value for FF_BASE_FACILITY.FACILITY_NAME
     *
     * @mbggenerated
     */
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName == null ? null : facilityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.OWNER_TYPE
     *
     * @return the value of FF_BASE_FACILITY.OWNER_TYPE
     *
     * @mbggenerated
     */
    public String getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.OWNER_TYPE
     *
     * @param ownerType the value for FF_BASE_FACILITY.OWNER_TYPE
     *
     * @mbggenerated
     */
    public void setOwnerType(String ownerType) {
        this.ownerType = ownerType == null ? null : ownerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SCOPE_TYPE
     *
     * @return the value of FF_BASE_FACILITY.SCOPE_TYPE
     *
     * @mbggenerated
     */
    public String getScopeType() {
        return scopeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SCOPE_TYPE
     *
     * @param scopeType the value for FF_BASE_FACILITY.SCOPE_TYPE
     *
     * @mbggenerated
     */
    public void setScopeType(String scopeType) {
        this.scopeType = scopeType == null ? null : scopeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.POSITION
     *
     * @return the value of FF_BASE_FACILITY.POSITION
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.POSITION
     *
     * @param position the value for FF_BASE_FACILITY.POSITION
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.BRAND
     *
     * @return the value of FF_BASE_FACILITY.BRAND
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.BRAND
     *
     * @param brand the value for FF_BASE_FACILITY.BRAND
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SPECIFICATION
     *
     * @return the value of FF_BASE_FACILITY.SPECIFICATION
     *
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SPECIFICATION
     *
     * @param specification the value for FF_BASE_FACILITY.SPECIFICATION
     *
     * @mbggenerated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.INSTALL_DATE
     *
     * @return the value of FF_BASE_FACILITY.INSTALL_DATE
     *
     * @mbggenerated
     */
    public Date getInstallDate() {
        return installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.INSTALL_DATE
     *
     * @param installDate the value for FF_BASE_FACILITY.INSTALL_DATE
     *
     * @mbggenerated
     */
    public void setInstallDate(Date installDate) {
        this.installDate = installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.ENABLE_DATE
     *
     * @return the value of FF_BASE_FACILITY.ENABLE_DATE
     *
     * @mbggenerated
     */
    public Date getEnableDate() {
        return enableDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.ENABLE_DATE
     *
     * @param enableDate the value for FF_BASE_FACILITY.ENABLE_DATE
     *
     * @mbggenerated
     */
    public void setEnableDate(Date enableDate) {
        this.enableDate = enableDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.DELIVERY_DATE
     *
     * @return the value of FF_BASE_FACILITY.DELIVERY_DATE
     *
     * @mbggenerated
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.DELIVERY_DATE
     *
     * @param deliveryDate the value for FF_BASE_FACILITY.DELIVERY_DATE
     *
     * @mbggenerated
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.WARRANTY_DATE
     *
     * @return the value of FF_BASE_FACILITY.WARRANTY_DATE
     *
     * @mbggenerated
     */
    public Date getWarrantyDate() {
        return warrantyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.WARRANTY_DATE
     *
     * @param warrantyDate the value for FF_BASE_FACILITY.WARRANTY_DATE
     *
     * @mbggenerated
     */
    public void setWarrantyDate(Date warrantyDate) {
        this.warrantyDate = warrantyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.RELEASE_DATE
     *
     * @return the value of FF_BASE_FACILITY.RELEASE_DATE
     *
     * @mbggenerated
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.RELEASE_DATE
     *
     * @param releaseDate the value for FF_BASE_FACILITY.RELEASE_DATE
     *
     * @mbggenerated
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SUPPLY_UNIT
     *
     * @return the value of FF_BASE_FACILITY.SUPPLY_UNIT
     *
     * @mbggenerated
     */
    public String getSupplyUnit() {
        return supplyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SUPPLY_UNIT
     *
     * @param supplyUnit the value for FF_BASE_FACILITY.SUPPLY_UNIT
     *
     * @mbggenerated
     */
    public void setSupplyUnit(String supplyUnit) {
        this.supplyUnit = supplyUnit == null ? null : supplyUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.REMARK
     *
     * @return the value of FF_BASE_FACILITY.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.REMARK
     *
     * @param remark the value for FF_BASE_FACILITY.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.FACILITY_STATUS
     *
     * @return the value of FF_BASE_FACILITY.FACILITY_STATUS
     *
     * @mbggenerated
     */
    public String getFacilityStatus() {
        return facilityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.FACILITY_STATUS
     *
     * @param facilityStatus the value for FF_BASE_FACILITY.FACILITY_STATUS
     *
     * @mbggenerated
     */
    public void setFacilityStatus(String facilityStatus) {
        this.facilityStatus = facilityStatus == null ? null : facilityStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.FACILITY_BELONG
     *
     * @return the value of FF_BASE_FACILITY.FACILITY_BELONG
     *
     * @mbggenerated
     */
    public String getFacilityBelong() {
        return facilityBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.FACILITY_BELONG
     *
     * @param facilityBelong the value for FF_BASE_FACILITY.FACILITY_BELONG
     *
     * @mbggenerated
     */
    public void setFacilityBelong(String facilityBelong) {
        this.facilityBelong = facilityBelong == null ? null : facilityBelong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.POSSESSOR
     *
     * @return the value of FF_BASE_FACILITY.POSSESSOR
     *
     * @mbggenerated
     */
    public String getPossessor() {
        return possessor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.POSSESSOR
     *
     * @param possessor the value for FF_BASE_FACILITY.POSSESSOR
     *
     * @mbggenerated
     */
    public void setPossessor(String possessor) {
        this.possessor = possessor == null ? null : possessor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.RESPONSOR
     *
     * @return the value of FF_BASE_FACILITY.RESPONSOR
     *
     * @mbggenerated
     */
    public String getResponsor() {
        return responsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.RESPONSOR
     *
     * @param responsor the value for FF_BASE_FACILITY.RESPONSOR
     *
     * @mbggenerated
     */
    public void setResponsor(String responsor) {
        this.responsor = responsor == null ? null : responsor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.ADDRESS
     *
     * @return the value of FF_BASE_FACILITY.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.ADDRESS
     *
     * @param address the value for FF_BASE_FACILITY.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SCRAP_DATE
     *
     * @return the value of FF_BASE_FACILITY.SCRAP_DATE
     *
     * @mbggenerated
     */
    public Date getScrapDate() {
        return scrapDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SCRAP_DATE
     *
     * @param scrapDate the value for FF_BASE_FACILITY.SCRAP_DATE
     *
     * @mbggenerated
     */
    public void setScrapDate(Date scrapDate) {
        this.scrapDate = scrapDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SCRAP_REASON
     *
     * @return the value of FF_BASE_FACILITY.SCRAP_REASON
     *
     * @mbggenerated
     */
    public String getScrapReason() {
        return scrapReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SCRAP_REASON
     *
     * @param scrapReason the value for FF_BASE_FACILITY.SCRAP_REASON
     *
     * @mbggenerated
     */
    public void setScrapReason(String scrapReason) {
        this.scrapReason = scrapReason == null ? null : scrapReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.RESPONSE_METHOD
     *
     * @return the value of FF_BASE_FACILITY.RESPONSE_METHOD
     *
     * @mbggenerated
     */
    public String getResponseMethod() {
        return responseMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.RESPONSE_METHOD
     *
     * @param responseMethod the value for FF_BASE_FACILITY.RESPONSE_METHOD
     *
     * @mbggenerated
     */
    public void setResponseMethod(String responseMethod) {
        this.responseMethod = responseMethod == null ? null : responseMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.IS_DELETED
     *
     * @return the value of FF_BASE_FACILITY.IS_DELETED
     *
     * @mbggenerated
     */
    public Float getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.IS_DELETED
     *
     * @param isDeleted the value for FF_BASE_FACILITY.IS_DELETED
     *
     * @mbggenerated
     */
    public void setIsDeleted(Float isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.VERSION
     *
     * @return the value of FF_BASE_FACILITY.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.VERSION
     *
     * @param version the value for FF_BASE_FACILITY.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SYS_CREATE_TIME
     *
     * @return the value of FF_BASE_FACILITY.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for FF_BASE_FACILITY.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(Date sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SYS_UPDATE_TIME
     *
     * @return the value of FF_BASE_FACILITY.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for FF_BASE_FACILITY.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(Date sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SYS_DELETE_TIME
     *
     * @return the value of FF_BASE_FACILITY.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for FF_BASE_FACILITY.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(Date sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SYS_CREATE_ID
     *
     * @return the value of FF_BASE_FACILITY.SYS_CREATE_ID
     *
     * @mbggenerated
     */
    public String getSysCreateId() {
        return sysCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SYS_CREATE_ID
     *
     * @param sysCreateId the value for FF_BASE_FACILITY.SYS_CREATE_ID
     *
     * @mbggenerated
     */
    public void setSysCreateId(String sysCreateId) {
        this.sysCreateId = sysCreateId == null ? null : sysCreateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SYS_UPDATE_ID
     *
     * @return the value of FF_BASE_FACILITY.SYS_UPDATE_ID
     *
     * @mbggenerated
     */
    public String getSysUpdateId() {
        return sysUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SYS_UPDATE_ID
     *
     * @param sysUpdateId the value for FF_BASE_FACILITY.SYS_UPDATE_ID
     *
     * @mbggenerated
     */
    public void setSysUpdateId(String sysUpdateId) {
        this.sysUpdateId = sysUpdateId == null ? null : sysUpdateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FF_BASE_FACILITY.SYS_DELETE_ID
     *
     * @return the value of FF_BASE_FACILITY.SYS_DELETE_ID
     *
     * @mbggenerated
     */
    public String getSysDeleteId() {
        return sysDeleteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FF_BASE_FACILITY.SYS_DELETE_ID
     *
     * @param sysDeleteId the value for FF_BASE_FACILITY.SYS_DELETE_ID
     *
     * @mbggenerated
     */
    public void setSysDeleteId(String sysDeleteId) {
        this.sysDeleteId = sysDeleteId == null ? null : sysDeleteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FF_BASE_FACILITY
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", facilityTypeCode=").append(facilityTypeCode);
        sb.append(", pkPropertyAreaId=").append(pkPropertyAreaId);
        sb.append(", facilityName=").append(facilityName);
        sb.append(", ownerType=").append(ownerType);
        sb.append(", scopeType=").append(scopeType);
        sb.append(", position=").append(position);
        sb.append(", brand=").append(brand);
        sb.append(", specification=").append(specification);
        sb.append(", installDate=").append(installDate);
        sb.append(", enableDate=").append(enableDate);
        sb.append(", deliveryDate=").append(deliveryDate);
        sb.append(", warrantyDate=").append(warrantyDate);
        sb.append(", releaseDate=").append(releaseDate);
        sb.append(", supplyUnit=").append(supplyUnit);
        sb.append(", remark=").append(remark);
        sb.append(", facilityStatus=").append(facilityStatus);
        sb.append(", facilityBelong=").append(facilityBelong);
        sb.append(", possessor=").append(possessor);
        sb.append(", responsor=").append(responsor);
        sb.append(", address=").append(address);
        sb.append(", scrapDate=").append(scrapDate);
        sb.append(", scrapReason=").append(scrapReason);
        sb.append(", responseMethod=").append(responseMethod);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", version=").append(version);
        sb.append(", sysCreateTime=").append(sysCreateTime);
        sb.append(", sysUpdateTime=").append(sysUpdateTime);
        sb.append(", sysDeleteTime=").append(sysDeleteTime);
        sb.append(", sysCreateId=").append(sysCreateId);
        sb.append(", sysUpdateId=").append(sysUpdateId);
        sb.append(", sysDeleteId=").append(sysDeleteId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}