package com.jml.serviceapi.dao;

import com.jml.serviceapi.domain.Clientdetails;
import java.util.List;

public interface ClientdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbggenerated
     */
    int insert(Clientdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbggenerated
     */
    Clientdetails selectByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbggenerated
     */
    List<Clientdetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Clientdetails record);
}