package com.jml.serviceapi.dao;

import com.jml.serviceapi.domain.OauthApprovals;
import java.util.List;

public interface OauthApprovalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated
     */
    int insert(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated
     */
    List<OauthApprovals> selectAll();
}