package com.jml.dao;

import com.jml.domain.OauthClientToken;

import java.util.List;

public interface OauthClientTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated
     */
    int insert(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbggenerated
     */
    List<OauthClientToken> selectAll();
}