package com.jml.dao;

import com.jml.serviceapi.domain.OauthRefreshToken;

import java.util.List;

public interface OauthRefreshTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int insert(OauthRefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    List<OauthRefreshToken> selectAll();
}