package com.jml.fixfunds.dao;

import com.jml.fixfunds.domain.FfBaseFacility;
import java.util.List;

public interface FfBaseFacilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FF_BASE_FACILITY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FF_BASE_FACILITY
     *
     * @mbggenerated
     */
    int insert(FfBaseFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FF_BASE_FACILITY
     *
     * @mbggenerated
     */
    FfBaseFacility selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FF_BASE_FACILITY
     *
     * @mbggenerated
     */
    List<FfBaseFacility> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FF_BASE_FACILITY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FfBaseFacility record);
}