#spring boot application
spring:
  application:
    name: dubbo-login
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbird
    username: hbird
    password: hbird

mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.jml.domain

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
  port: 9091

dubbo:
  scan:
    #base packages to scan dubbo components
    base-packages: com.jml.service
  application:
    #dubbo config properties
    ##application config bean
    id: dubbo-provider-login
    name: dubbo-provider-login
   #protocol config bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12346
  registry:
    address: zookeeper://127.0.0.1:2181

logging:
  level:
    root: WARN
    sample:
      mybatis:
        mapper: TRACE

