package com.jml.serviceapi.dto;

import java.io.Serializable;
import java.util.Date;

public class OauthApprovals implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.clientId
     *
     * @mbggenerated
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.expiresAt
     *
     * @mbggenerated
     */
    private Date expiresat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.lastModifiedAt
     *
     * @mbggenerated
     */
    private Date lastmodifiedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_approvals
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.userId
     *
     * @return the value of oauth_approvals.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.userId
     *
     * @param userid the value for oauth_approvals.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.clientId
     *
     * @return the value of oauth_approvals.clientId
     *
     * @mbggenerated
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.clientId
     *
     * @param clientid the value for oauth_approvals.clientId
     *
     * @mbggenerated
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.scope
     *
     * @return the value of oauth_approvals.scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.scope
     *
     * @param scope the value for oauth_approvals.scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.status
     *
     * @return the value of oauth_approvals.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.status
     *
     * @param status the value for oauth_approvals.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.expiresAt
     *
     * @return the value of oauth_approvals.expiresAt
     *
     * @mbggenerated
     */
    public Date getExpiresat() {
        return expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.expiresAt
     *
     * @param expiresat the value for oauth_approvals.expiresAt
     *
     * @mbggenerated
     */
    public void setExpiresat(Date expiresat) {
        this.expiresat = expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.lastModifiedAt
     *
     * @return the value of oauth_approvals.lastModifiedAt
     *
     * @mbggenerated
     */
    public Date getLastmodifiedat() {
        return lastmodifiedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.lastModifiedAt
     *
     * @param lastmodifiedat the value for oauth_approvals.lastModifiedAt
     *
     * @mbggenerated
     */
    public void setLastmodifiedat(Date lastmodifiedat) {
        this.lastmodifiedat = lastmodifiedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", clientid=").append(clientid);
        sb.append(", scope=").append(scope);
        sb.append(", status=").append(status);
        sb.append(", expiresat=").append(expiresat);
        sb.append(", lastmodifiedat=").append(lastmodifiedat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}